return {
    'wbthomason/packer.nvim',
    'bfredl/nvim-miniyank',
    {'junegunn/fzf', dir = '~/.fzf', build = './install --all'},
    'junegunn/fzf.vim',
    'mattn/emmet-vim',
    'mfussenegger/nvim-dap',
    'mfussenegger/nvim-jdtls',
    'mhartington/formatter.nvim',
    'mrjones2014/nvim-ts-rainbow',
    'nvim-lua/popup.nvim',
    'nvim-lua/plenary.nvim',
    'peitalin/vim-jsx-typescript',
    'ray-x/lsp_signature.nvim',
    'simrat39/rust-tools.nvim',
    'theHamsta/nvim-dap-virtual-text',
    'tommcdo/vim-exchange',
    'tpope/vim-commentary',
    {'tpope/vim-dispatch', lazy = true, cmd = {'Dispatch', 'Make', 'Focus', 'Start'}},
    'tpope/vim-fugitive',
    'tpope/vim-dadbod',
    'tpope/vim-repeat',
    'tpope/vim-surround',
}
